<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\FusionRpg.Core.Tests.Shared\CoreTests.Shared.props" />
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>FusionRpg.Core.Tests</RootNamespace>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FusionRpg.Core\FusionRpg.Core.csproj" />
  </ItemGroup>
</Project>
