using System.Text.Json;
using FusionRpg.Core.Creatures;
using FusionRpg.Core.Stats.Derived;

namespace FusionRpg.Core.Items.Materials;

/// <summary>
/// The five ORIGINALLY shipped spend classes (`salvage-craft` §1, item module 14), joined since by
/// <see cref="Trophy"/> (species-gear-chain T33) and <see cref="Assurance"/> (T40) — each its own
/// ask-first boundary, filed against `ssot-materials-crafting.md` §3.1 with the same question every
/// extension must answer: "which of the existing classes is unanswerable for my spend?" — not "I
/// want another currency". Closed at seven today; an eighth is the next ask-first boundary.
/// </summary>
public enum MaterialClass
{
    /// <summary>"May I act at all?" — the flat fee. A ledger balance, not a material id, which is why
    /// <see cref="MaterialCatalog.All"/> is 27 and not 28.</summary>
    Souls = 0,

    /// <summary>"How good may it be?" — the rarity ceiling. `shard.{rung}`, ten ids, already shipped.</summary>
    Shard,

    /// <summary>"What is it made of?" — frame-locked, graded by item level. `substrate.{frame}.{grade}`.</summary>
    Substrate,

    /// <summary>"What flavour?" — element direction, no magnitude. `essence.{element}`, six ids, shipped.</summary>
    Essence,

    /// <summary>"What am I doing to it?" — make / improve / re-randomise. `catalyst.{verb}`.</summary>
    Catalyst,

    /// <summary>
    /// species-gear-chain T33 (`species-materials`, filed against `ssot-materials-crafting.md` §3.1
    /// under owner rulings R-SC1/R9 — a provenance class with species/family scopes, not a contested
    /// slot). "What did this come from?" — provenance. NONE of the other five asks this: Shard is a
    /// rarity ceiling, Essence is element direction with no magnitude, Catalyst is the verb, and
    /// Substrate is {frame}.{grade} at 8 ids — folding species into it would multiply a graded axis
    /// by the whole corpus. Ids are `trophy.{species|family}...`, minted by a deterministic planner
    /// from two seedsmith parameters (`gk-core/data/tuning/species-material-run.v1.json`) and injected by the
    /// host — never listed here, and never counted in the closed 27 (a population, not a vocabulary).
    /// </summary>
    Trophy,

    /// <summary>
    /// species-gear-chain T40 (`craft-assurance`, filed against `ssot-materials-crafting.md` §3.1,
    /// answered by R-G1). "How much variance do I accept on this attempt?" — none of the other six
    /// asks this: Catalyst names the VERB, not the risk carried into it. A CLOSED three-id vocabulary
    /// (`assurance.assure` / `.protect` / `.repair`), generated by `materialgen` from a shape table
    /// exactly like the five originally-shipped classes — never counted in the closed 27 (that count
    /// is scoped to those five by definition), but a real closed set of its own, pinned at 3.
    /// </summary>
    Assurance,
}

public sealed class MaterialVocabularyRejection : Exception
{
    public MaterialVocabularyRejection(string message) : base(message) { }
}

/// <summary>
/// The 27-id closed cost vocabulary every other sink spends in (`salvage-craft` §1). Wraps
/// <see cref="CreatureMaterialCatalog"/> for the sixteen ids that already ship rather than re-minting
/// them — the spec's own instruction, and the reason the four legacy shard ids keep resolving here
/// exactly as they do there.
///
/// <para>⛔ <b>Order matters and it is the SPEND order</b> (`salvage-craft` §"The spend transaction",
/// step 4): souls → shard → substrate → essence → catalyst. A partial failure then always fails at
/// the same point, so two logs of one refusal are byte-comparable. <see cref="MaterialClass"/>'s
/// member order IS that order, and <see cref="ClassRank"/> is what the store sorts on.</para>
/// </summary>
public static class MaterialCatalog
{
    /// <summary>The two frames a substrate can be made of. Not a third vocabulary —
    /// <see cref="ItemFrame"/> is the shipped enum and this is its lower-case id form.</summary>
    public static readonly IReadOnlyList<string> SubstrateFrames = new[] { "humanoid", "plant" };

    /// <summary>The four substrate grades, ordinal 1..4. Structural, not a balance list: a fifth
    /// grade is a new material id and a new authored row, never a tuning edit.</summary>
    public static readonly IReadOnlyList<string> SubstrateGrades = new[] { "crude", "sound", "fine", "prime" };

    /// <summary>The three catalyst verbs (§1 row 5). A fourth is an ask-first boundary.</summary>
    public static readonly IReadOnlyList<string> CatalystVerbs = new[] { "forge", "temper", "flux" };

    /// <summary>species-gear-chain T40 — the three assurance ids. A fourth is an ask-first boundary,
    /// the same posture <see cref="CatalystVerbs"/> already holds for its own closed three.</summary>
    public static readonly IReadOnlyList<string> AssuranceVerbs = new[] { "assure", "protect", "repair" };

    static IReadOnlyList<string>? _all;

    /// <summary>
    /// Every ISSUABLE material id, in class order: shard ×10, substrate ×8, essence ×6, catalyst ×3.
    /// Twenty-seven. Souls carry no id — they are a ledger balance (`rpg_soul_ledger`), which is the
    /// whole reason the count is 27 rather than 28.
    /// </summary>
    // Lazy for the same reason CreatureMaterialCatalog is: it reads another catalog's statics, and a
    // static-initialiser cycle is a silent empty list rather than a throw.
    public static IReadOnlyList<string> All => _all ??= Build();

    static IReadOnlyList<string> Build()
    {
        var ids = new List<string>();

        // The sixteen shipped ids come from CreatureMaterialCatalog, never re-derived here — the spec's
        // "reuse, not re-mint" line. Its own order is essence-then-shard; this list is class order.
        foreach (var rarity in CreatureRarityLadder.All)
            ids.Add($"shard.{rarity.ToId()}");

        foreach (var frame in SubstrateFrames)
            for (var g = 0; g < SubstrateGrades.Count; g++)
                ids.Add($"substrate.{frame}.{SubstrateGrades[g]}");

        foreach (var element in ElementRoster.Concrete)
            ids.Add($"essence.{element.ToElementId()}");

        foreach (var verb in CatalystVerbs)
            ids.Add($"catalyst.{verb}");

        return ids;
    }

    static HashSet<string>? _issuable;
    static HashSet<string> Issuable => _issuable ??= new HashSet<string>(All, StringComparer.Ordinal);

    // species-gear-chain T34b: the trophy id registry, host-injected at boot (Core never reads a
    // file, tunables-ssot §7.2). Re-assignable, matching every other tuning/registry hub in this
    // codebase (CreatureYieldTuningHub, ExpeditionTuningHub) rather than throwing on a second call —
    // a test may configure its own fixture set, and a live re-plan is a host restart, never a runtime
    // replace, so idempotent re-assignment costs nothing in production either.
    static IReadOnlySet<string>? _trophyRegistry;
    static IReadOnlySet<(string Scope, int Slot)>? _trophyScopeSlots;

    /// <summary>
    /// Host-injected at boot from the deterministic planner's own generated output
    /// (<c>gk-data/packs/fusion/data/seed/items/materials/trophy-registry.json</c>, species-gear-chain T34) — the set of
    /// every CONCRETE trophy id (<c>trophy.{species|family}.{scopeKey}.{slot}</c>) this build
    /// recognizes. <see cref="ClassOf"/> resolves a trophy id to <see cref="MaterialClass.Trophy"/>
    /// only if this set holds it; a scope TOKEN (<c>trophy.{species|family}.{slot}</c>, the shape a
    /// recipe AUTHORS — see <see cref="TryParseTrophyScopeToken"/>) is a structural, never
    /// registry-checked, concept and resolves regardless of this set's contents.
    ///
    /// <para>species-gear-chain T30b: also derives the (scope, slot) pairs
    /// <see cref="IsTrophySlotIssuable"/> answers from — computed once here rather than scanned per
    /// call, since a drop-table IMPORT can check many entries.</para>
    /// </summary>
    public static void ConfigureTrophyRegistry(IReadOnlySet<string> materialIds)
    {
        _trophyRegistry = materialIds ?? throw new ArgumentNullException(nameof(materialIds));
        var scopeSlots = new HashSet<(string, int)>();
        foreach (var id in materialIds)
        {
            var parts = id.Split('.');
            if (parts.Length == 4 && int.TryParse(parts[3], out var slot))
                scopeSlots.Add((parts[1], slot));
        }
        _trophyScopeSlots = scopeSlots;
    }

    /// <summary>True only for a CONCRETE id the injected registry holds — never true for a scope
    /// token, and never true before <see cref="ConfigureTrophyRegistry"/> has run.</summary>
    public static bool IsTrophyId(string? materialId) =>
        materialId != null && _trophyRegistry != null && _trophyRegistry.Contains(materialId);

    /// <summary>
    /// species-gear-chain T30b (`creature-drop-tables` d) — whether ANY scopeKey in the injected
    /// registry carries this (scope, slot) pair, i.e. whether <paramref name="slot"/> is inside
    /// <c>1..perSpecies</c>/<c>1..perFamily</c> WITHOUT this file (or its caller,
    /// <c>DropTableValidator</c>) ever reading those two generation-time-only numbers directly — a
    /// parametric drop-table entry (T30b's own shape: <c>trophy_scope</c> + <c>trophy_slot</c>, no
    /// <c>scopeKey</c> yet, since the killed species/family is only known at draw time) can only be
    /// bounds-checked against the registry's own contents, not a count this class never mints.
    /// </summary>
    public static bool IsTrophySlotIssuable(string scope, int slot) =>
        _trophyScopeSlots != null && _trophyScopeSlots.Contains((scope, slot));

    /// <summary>
    /// species-gear-chain T34: `trophy.{scope}.{scopeKey}.{slot}` — parses the JSON the planner wrote
    /// (<c>{"_meta": {...}, "entries": [{"materialId": ..., ...}, ...]}</c>) into the flat id set
    /// <see cref="ConfigureTrophyRegistry"/> takes. The one place this shape is read; a host boot
    /// calls this once, then Configure, exactly like <c>MaterialTuning.Parse</c>'s own pattern.
    /// </summary>
    public static IReadOnlySet<string> ParseTrophyRegistryIds(string json)
    {
        if (string.IsNullOrWhiteSpace(json))
            throw new MaterialVocabularyRejection("trophy registry: empty document");

        JsonDocument doc;
        try { doc = JsonDocument.Parse(json); }
        catch (JsonException ex) { throw new MaterialVocabularyRejection($"trophy registry: not valid JSON — {ex.Message}"); }

        using (doc)
        {
            if (!doc.RootElement.TryGetProperty("entries", out var entries) || entries.ValueKind != JsonValueKind.Array)
                throw new MaterialVocabularyRejection("trophy registry: missing or non-array 'entries'");

            var ids = new HashSet<string>(StringComparer.Ordinal);
            foreach (var entry in entries.EnumerateArray())
            {
                if (!entry.TryGetProperty("materialId", out var idEl) || idEl.ValueKind != JsonValueKind.String)
                    throw new MaterialVocabularyRejection("trophy registry: an entry is missing string 'materialId'");
                var id = idEl.GetString()!;
                if (!ids.Add(id))
                    throw new MaterialVocabularyRejection($"trophy registry: duplicate materialId '{id}'");
            }
            return ids;
        }
    }

    /// <summary>
    /// The AUTHORED shape a recipe's cost line names for a trophy leg — <c>trophy.species.{slot}</c>
    /// or <c>trophy.family.{slot}</c>, ONE dot fewer than a concrete id
    /// (<c>trophy.{scope}.{scopeKey}.{slot}</c>), because a recipe never names a literal per-species
    /// id (904 recipes would be needed); it names which scope and which of that scope's
    /// <c>perSpecies</c>/<c>perFamily</c> slots it demands, resolved against the bound piece's own
    /// species at cost time (<see cref="MaterialRecipeCatalog.Resolve"/>, species-gear-chain T34b).
    /// </summary>
    public static bool TryParseTrophyScopeToken(string? materialId, out string scope, out int slot)
    {
        scope = ""; slot = 0;
        if (string.IsNullOrEmpty(materialId) || !materialId.StartsWith("trophy.", StringComparison.Ordinal))
            return false;

        var parts = materialId.Split('.');
        if (parts.Length != 3) return false; // "trophy", scope, slot — a concrete id has 4 parts
        if (parts[1] != "species" && parts[1] != "family") return false;
        if (!int.TryParse(parts[2], out var parsedSlot) || parsedSlot < 1) return false;

        scope = parts[1];
        slot = parsedSlot;
        return true;
    }

    /// <summary>The concrete id a scope token resolves to once the bound piece's own species (or one
    /// of its families) is known. The inverse of the grammar <see cref="TryParseTrophyScopeToken"/>
    /// parses.</summary>
    public static string ComposeTrophyId(string scope, string scopeKey, int slot) =>
        $"trophy.{scope}.{scopeKey}.{slot}";

    static HashSet<string>? _assuranceIds;

    /// <summary>species-gear-chain T40 — the three concrete assurance ids
    /// (<c>assurance.assure</c>/<c>.protect</c>/<c>.repair</c>), built once from
    /// <see cref="AssuranceVerbs"/>. A closed set, never host-injected (unlike <see cref="Trophy"/>'s
    /// population) — <c>materialgen</c> authors display content for exactly these three, and nothing
    /// else ever grows this set at runtime.</summary>
    static HashSet<string> AssuranceIds => _assuranceIds ??=
        new HashSet<string>(AssuranceVerbs.Select(v => $"assurance.{v}"), StringComparer.Ordinal);

    /// <summary>True only for one of the three closed assurance ids.</summary>
    public static bool IsAssuranceId(string? materialId) =>
        materialId != null && AssuranceIds.Contains(materialId);

    /// <summary>True for an id this build will mint. The four legacy shard ids are deliberately
    /// <b>false</b> here and <b>true</b> in <see cref="IsKnown"/> — a saved reference still resolves,
    /// but nothing new is ever created in the retired vocabulary.
    ///
    /// <para>species-gear-chain T34b: also true for a CONCRETE trophy id the injected registry holds
    /// — a trophy is mintable too, just via the creature-kill economy (T34c) rather than this build's
    /// own closed <see cref="All"/> list. Never true for a trophy SCOPE TOKEN, which is an authored
    /// directive, not an issuable inventory item.</para>
    ///
    /// <para>species-gear-chain T40: also true for one of the three closed assurance ids.</para></summary>
    public static bool IsIssuable(string? materialId) =>
        materialId != null &&
        (Issuable.Contains(materialId) || IsTrophyId(materialId) || IsAssuranceId(materialId));

    /// <summary>
    /// True for an issuable id OR one of the four legacy shard ids (`shard.common` / `rare` / `epic` /
    /// `legendary`), which stay resolvable for one release so a stale client or a saved reference does
    /// not hard-fail (`spec-rarity-migration.md` §4 point 4). Delegates to
    /// <see cref="CreatureMaterialCatalog.IsKnown"/> for those rather than re-listing them.
    /// </summary>
    public static bool IsKnown(string? materialId) =>
        IsIssuable(materialId) || (materialId != null && CreatureMaterialCatalog.IsKnown(materialId));

    /// <summary>True only for the four retired band ids — resolvable, never minted, and never a legal
    /// cost line, because a recipe demanding one is a recipe nothing can ever pay.</summary>
    public static bool IsLegacyShardId(string? materialId) =>
        materialId != null &&
        materialId.StartsWith("shard.", StringComparison.Ordinal) &&
        LegacyCreatureRarityIds.IsLegacyId(materialId.Substring("shard.".Length));

    /// <summary>
    /// Which class an id belongs to. Throws on anything outside the closed vocabulary — including a
    /// <b>source-tagged</b> id such as <c>essence.fire.pvz</c>, which the Boundaries list forbids
    /// outright: the injector enriches, it never gates (SC8), so a PvZ-exclusive material id would
    /// make the lawn a required source for a web operation.
    /// </summary>
    public static MaterialClass ClassOf(string materialId)
    {
        if (string.IsNullOrWhiteSpace(materialId))
            throw new MaterialVocabularyRejection("material id is empty");

        var dots = materialId.Count(c => c == '.');

        if (materialId.StartsWith("shard.", StringComparison.Ordinal) && dots == 1 && IsKnown(materialId))
            return MaterialClass.Shard;

        if (materialId.StartsWith("substrate.", StringComparison.Ordinal) && dots == 2 && IsIssuable(materialId))
            return MaterialClass.Substrate;

        if (materialId.StartsWith("essence.", StringComparison.Ordinal) && dots == 1 && IsIssuable(materialId))
            return MaterialClass.Essence;

        if (materialId.StartsWith("catalyst.", StringComparison.Ordinal) && dots == 1 && IsIssuable(materialId))
            return MaterialClass.Catalyst;

        // species-gear-chain T34b: a trophy is EITHER a structural scope token (author-time, never
        // registry-checked — a recipe corpus row) OR a concrete id the host-injected registry holds
        // (resolve-time, T34's own generated output). Neither shape needs a `dots`-count check above
        // — TryParseTrophyScopeToken and the registry membership check are already exact.
        if (materialId.StartsWith("trophy.", StringComparison.Ordinal) &&
            (TryParseTrophyScopeToken(materialId, out _, out _) || IsTrophyId(materialId)))
            return MaterialClass.Trophy;

        if (materialId.StartsWith("assurance.", StringComparison.Ordinal) && dots == 1 && IsAssuranceId(materialId))
            return MaterialClass.Assurance;

        throw new MaterialVocabularyRejection(
            $"material id '{materialId}' is not in the 27-id closed vocabulary, is not a valid trophy " +
            "scope token (trophy.species.N / trophy.family.N), and is not a concrete trophy id the " +
            "injected registry holds " +
            "(a source-tagged id like 'essence.fire.pvz' is refused here by design — the injector enriches, it never gates)");
    }

    /// <summary>The fixed spend order, as a sort key. Souls first, catalyst last.</summary>
    public static int ClassRank(MaterialClass cls) => (int)cls;

    /// <summary>`substrate.{frame}.{grade}` for a frame id and an ordinal grade 1..4. Throws rather
    /// than clamping an out-of-range grade — a grade-5 request is a caller bug, and a silent clamp to
    /// prime would hand out the exact material the grade lock exists to protect.</summary>
    public static string SubstrateId(string frame, int grade)
    {
        if (!SubstrateFrames.Contains(frame, StringComparer.Ordinal))
            throw new MaterialVocabularyRejection($"substrate frame '{frame}' is not one of humanoid/plant");
        if (grade < 1 || grade > SubstrateGrades.Count)
            throw new MaterialVocabularyRejection($"substrate grade {grade} is outside 1..{SubstrateGrades.Count}");
        return $"substrate.{frame}.{SubstrateGrades[grade - 1]}";
    }

    /// <summary>The ordinal grade 1..4 carried by a substrate id, or 0 if it is not a substrate.</summary>
    public static int GradeOf(string materialId)
    {
        if (!materialId.StartsWith("substrate.", StringComparison.Ordinal)) return 0;
        var lastDot = materialId.LastIndexOf('.');
        if (lastDot < 0) return 0;
        var idx = SubstrateGrades.ToList().IndexOf(materialId.Substring(lastDot + 1));
        return idx < 0 ? 0 : idx + 1;
    }

    /// <summary>The frame id carried by a substrate id, or null.</summary>
    public static string? FrameOf(string materialId)
    {
        if (!materialId.StartsWith("substrate.", StringComparison.Ordinal)) return null;
        var parts = materialId.Split('.');
        return parts.Length == 3 && SubstrateFrames.Contains(parts[1], StringComparer.Ordinal) ? parts[1] : null;
    }

    public static string ShardId(CreatureRarity rarity) => $"shard.{rarity.ToId()}";

    public static string EssenceId(string elementId) => $"essence.{elementId}";

    public static string CatalystId(string verb) => $"catalyst.{verb}";

    public static string AssuranceId(string verb) => $"assurance.{verb}";
}
