using System.Text;
using System.Text.RegularExpressions;

namespace FusionRpg.Tools.FileMove;

/// <summary>`core-split-apply` A4 — one explicit filesystem operation in a split plan.</summary>
/// <param name="Kind">What the operation does.</param>
/// <param name="Path">Repo-relative destination path — for <see cref="SplitOpKind.MoveFile"/> the
/// destination, for <see cref="SplitOpKind.CreateDirectory"/> the directory.</param>
/// <param name="From">Repo-relative source path — set only for <see cref="SplitOpKind.MoveFile"/>.</param>
/// <param name="Before">Bytes the path holds today. Null for <see cref="SplitOpKind.CreateFile"/>,
/// <see cref="SplitOpKind.CreateDirectory"/> and <see cref="SplitOpKind.MoveFile"/> (nothing sits at
/// the destination yet).</param>
/// <param name="After">Bytes the path will hold. Null for <see cref="SplitOpKind.CreateDirectory"/>
/// and for <see cref="SplitOpKind.MoveFile"/> — a move never reads the source into a string, so the
/// plan does not carry a text copy of it; <see cref="SplitExecutor"/> copies the source's bytes
/// directly.</param>
public sealed record SplitOp(SplitOpKind Kind, string Path, string? From, byte[]? Before, byte[]? After);

public enum SplitOpKind { CreateFile, ModifyFile, MoveFile, CreateDirectory }

/// <summary>
/// The full change set for one manifest project, computed before anything is written — the same
/// "everything decided in Plan" shape as <see cref="MovePlan"/>/<see cref="FileMover"/>, so a dry run
/// and `--apply` can never disagree about what happens.
/// </summary>
/// <param name="ProjectName">The manifest project this plan applies.</param>
/// <param name="Ops">Every operation, in apply order.</param>
/// <param name="Edits">A <see cref="PlannedEdit"/> view of the CreateFile/ModifyFile ops only, decoded
/// as UTF-8 text, for a dry run to print a readable diff. Moves are printed from <see cref="Ops"/>
/// directly — a move's "edit" is not a text change, so forcing it through <see cref="PlannedEdit"/>
/// would print a source path where content belongs.</param>
/// <param name="Refusal">Non-null when the plan must not be applied; nothing is written.</param>
public sealed record SplitPlan(
    string ProjectName,
    IReadOnlyList<SplitOp> Ops,
    IReadOnlyList<PlannedEdit> Edits,
    string? Refusal)
{
    public bool IsRefused => Refusal is not null;
}

/// <summary>
/// `core-split-apply` A2–A4 — turns one manifest project into a <see cref="SplitPlan"/>. Every
/// filesystem-shaped question is an injected delegate (the same seam <see cref="FileMover"/> uses for
/// `readText`/`enumerateFiles`), so planning — including the dirty-path refusal — runs in memory over a
/// synthetic tree (`core-split-apply` Testing: F1, F7, F8).
///
/// <para><b>Never calls <see cref="FileMover"/>'s move planner.</b> A split moves bytes unchanged and
/// never rewrites a namespace (A2) — <see cref="MovePlanner.RewriteNamespace"/> would "fix" the 25
/// files whose namespace does not match their folder (map G17), which is exactly the case a split must
/// leave alone.</para>
/// </summary>
public static class SplitPlanner
{
    const string GeneratedHeader =
        "// Generated by `tools/FileMove split` from the manifest -- never hand-edited.\r\n"
        + "// Regenerate by re-running the split tool; a hand edit is reverted by the next run.\r\n";

    /// <summary> and as a whole line — leading indent and
    /// trailing newline included — in both shapes MSBuild allows: self-closing, and paired with
    /// `IncludeAssets`/`PrivateAssets` children.
    ///
    /// <para>Matching only the self-closing shape is a defect this replaced: the residual's own
    /// `coverlet.collector` and `xunit.runner.visualstudio` are PAIRED elements, so they stayed in the
    /// residual and never reached the shared props. The new project then had no xunit test adapter,
    /// `dotnet test` reported "No test is available in …" and <b>exited 0</b> — so the first real
    /// increment was kept with the new project running zero tests, which is the precise quiet failure
    /// this module exists to prevent (`core-split-apply` A2: the props carries "the package
    /// references", `FusionRpg.Core.Tests.csproj:10-22`).</para></summary>
    static readonly Regex PackageReferenceElement = new(
        @"^[ \t]*<PackageReference(?=[\s/>])[^>]*/>[ \t]*\r?\n"
        + @"|^[ \t]*<PackageReference(?=[\s/>])[^>]*/>[ \t]*$"
        + @"|^[ \t]*<PackageReference(?=[\s/>])[^>]*>[\s\S]*?</PackageReference>[ \t]*\r?\n"
        + @"|^[ \t]*<PackageReference(?=[\s/>])[^>]*>[\s\S]*?</PackageReference>[ \t]*$",
        RegexOptions.Compiled | RegexOptions.Multiline);

    /// <summary>A whole-line <c>Compile</c>/<c>None</c> item, for the same reason as
    /// <see cref="PackageReferenceLine"/>: a removed explicit item must take its line with it.</summary>
    static readonly Regex ExplicitItemLine = new(
        @"^[ \t]*<(Compile|None)\s+Include\s*=\s*""(?<inc>[^""]+)""[^>]*/>[ \t]*\r?\n",
        RegexOptions.Compiled | RegexOptions.Multiline);

    static readonly Regex ProjectOpenTag = new(@"<Project\b[^>]*>", RegexOptions.Compiled);

    static readonly Regex TestsFolder = new(
        @"<Folder\s+Name\s*=\s*""/tests/""\s*>[\s\S]*?</Folder>", RegexOptions.Compiled);

    /// <param name="manifest">The (already A1-validated) manifest.</param>
    /// <param name="projectName">Which manifest project to plan this increment.</param>
    /// <param name="filesMatching">Given an `include`/`shared` glob (relative to
    /// `tests/&lt;residual&gt;/`), the repo-relative-to-residual files it matches.</param>
    /// <param name="readBytes">Reads a repo-relative file's current bytes.</param>
    /// <param name="fileExists">Does a repo-relative file exist today?</param>
    /// <param name="dirtyPaths">The repo-relative paths `git status --porcelain` reports as changed
    /// right now. Injected so the refusal runs in memory (F7).</param>
    public static SplitPlan Plan(
        SplitManifest manifest,
        string projectName,
        Func<string, IReadOnlyList<string>> filesMatching,
        Func<string, byte[]> readBytes,
        Func<string, bool> fileExists,
        Func<IReadOnlyList<string>> dirtyPaths)
    {
        var project = manifest.Projects.FirstOrDefault(
            p => string.Equals(p.Name, projectName, StringComparison.Ordinal));
        if (project is null)
            return Refuse(projectName, $"manifest declares no project named '{projectName}'");

        var residualCsprojPath = $"tests/{manifest.Residual}/{manifest.Residual}.csproj";
        var slnxPath = "FusionRpg.slnx";
        var attributeFilePath = "src/FusionRpg.Core/InternalsVisibleTo.CoreTests.cs";

        if (!fileExists(residualCsprojPath))
            return Refuse(projectName, $"residual csproj '{residualCsprojPath}' does not exist");
        if (!fileExists(slnxPath))
            return Refuse(projectName, $"'{slnxPath}' does not exist");

        var sharedName = LastSegment(manifest.SharedDir);
        var sharedPropsPath = $"{manifest.SharedDir}/CoreTests.Shared.props";
        var isFirstIncrement = !fileExists(sharedPropsPath);

        var residualCsprojBytes = readBytes(residualCsprojPath);
        var residualCsprojText = Utf8Text(residualCsprojBytes);

        // A4 extension 1 — a defensive cycle check, restated honestly: the manifest rules already
        // enforced (references exist, are under src/tools, and are a subset of what the residual
        // already references, `SplitManifestValidator`) are the real protection, and nothing references
        // a test project, so this can never actually find a cycle. It still runs, against the local
        // graph the residual csproj and each direct reference's own csproj already give us, so the
        // invariant is checked rather than merely asserted in a comment.
        var localGraphFiles = new List<string> { residualCsprojPath };
        localGraphFiles.AddRange(project.References);
        var localGraph = new AssemblyGraph(localGraphFiles, p =>
            p == residualCsprojPath ? residualCsprojText : Utf8Text(readBytes(p)));
        foreach (var reference in project.References)
        {
            var refAssembly = Path.GetFileNameWithoutExtension(reference);
            var cycle = localGraph.FindPath(refAssembly, manifest.Residual);
            if (cycle is not null)
                return Refuse(projectName,
                    $"reference graph shows {string.Join(" -> ", cycle)} already reaches the residual "
                    + $"'{manifest.Residual}' -- moving files into '{projectName}' needs investigation "
                    + "before proceeding");
        }

        var ops = new List<SplitOp>();
        var projectDir = $"tests/{projectName}";

        ops.Add(new SplitOp(SplitOpKind.CreateDirectory, projectDir, null, null, null));
        if (isFirstIncrement)
            ops.Add(new SplitOp(SplitOpKind.CreateDirectory, manifest.SharedDir, null, null, null));

        var csprojText = BuildProjectCsproj(manifest, project, sharedName);
        ops.Add(new SplitOp(SplitOpKind.CreateFile, $"{projectDir}/{projectName}.csproj", null,
            null, Utf8(csprojText)));

        if (isFirstIncrement)
        {
            var propsText = BuildSharedProps(manifest, residualCsprojText);
            ops.Add(new SplitOp(SplitOpKind.CreateFile, sharedPropsPath, null, null, Utf8(propsText)));
        }

        var attributeBefore = fileExists(attributeFilePath) ? readBytes(attributeFilePath) : null;
        var attributeAfter = Utf8(BuildInternalsVisibleTo(manifest));
        ops.Add(new SplitOp(
            attributeBefore is null ? SplitOpKind.CreateFile : SplitOpKind.ModifyFile,
            attributeFilePath, null, attributeBefore, attributeAfter));

        if (isFirstIncrement)
        {
            var editedResidual = EditResidualCsproj(residualCsprojText, manifest, sharedName);
            ops.Add(new SplitOp(SplitOpKind.ModifyFile, residualCsprojPath, null,
                residualCsprojBytes, Utf8(editedResidual)));

            foreach (var pattern in manifest.Shared)
            foreach (var relative in filesMatching(pattern))
                ops.Add(new SplitOp(SplitOpKind.MoveFile, $"{manifest.SharedDir}/{relative}",
                    $"tests/{manifest.Residual}/{relative}", null, null));
        }

        var claimed = new List<string>();
        foreach (var pattern in project.Include)
        foreach (var relative in filesMatching(pattern))
            if (!claimed.Contains(relative, StringComparer.OrdinalIgnoreCase))
                claimed.Add(relative);

        foreach (var relative in claimed)
            ops.Add(new SplitOp(SplitOpKind.MoveFile, $"{projectDir}/{relative}",
                $"tests/{manifest.Residual}/{relative}", null, null));

        var slnxBytes = readBytes(slnxPath);
        var editedSlnx = AddSlnxEntry(Utf8Text(slnxBytes), projectName);
        if (editedSlnx is null)
            return Refuse(projectName, $"'{slnxPath}' has no /tests/ folder to add the entry to");
        ops.Add(new SplitOp(SplitOpKind.ModifyFile, slnxPath, null, slnxBytes, Utf8(editedSlnx)));

        var touchedFiles = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var touchedDirs = new List<string> { projectDir };
        if (isFirstIncrement) touchedDirs.Add(manifest.SharedDir);

        foreach (var op in ops)
        {
            if (op.Kind is SplitOpKind.CreateDirectory) continue;
            touchedFiles.Add(op.Path);
            if (op.From is not null) touchedFiles.Add(op.From);
        }

        var dirty = dirtyPaths();
        var offender = dirty.FirstOrDefault(d =>
            touchedFiles.Contains(d)
            || touchedDirs.Any(dir => d.StartsWith(dir + "/", StringComparison.OrdinalIgnoreCase)
                                      || string.Equals(d, dir, StringComparison.OrdinalIgnoreCase)));
        if (offender is not null)
            return Refuse(projectName,
                $"'{offender}' has uncommitted changes; commit or revert it before splitting '{projectName}'");

        var edits = ops
            .Where(op => op.Kind is SplitOpKind.CreateFile or SplitOpKind.ModifyFile)
            .Select(op => new PlannedEdit(
                op.Path,
                op.Before is null ? "" : Utf8Text(op.Before),
                Utf8Text(op.After!),
                op.Kind == SplitOpKind.CreateFile ? "created" : "modified"))
            .ToList();

        return new SplitPlan(projectName, ops, edits, Refusal: null);
    }

    static SplitPlan Refuse(string projectName, string reason) =>
        new(projectName, Array.Empty<SplitOp>(), Array.Empty<PlannedEdit>(), reason);

    static byte[] Utf8(string text) => Encoding.UTF8.GetBytes(text);
    static string Utf8Text(byte[] bytes) => Encoding.UTF8.GetString(bytes);

    static string LastSegment(string repoRelativePath)
    {
        var idx = repoRelativePath.LastIndexOf('/');
        return idx < 0 ? repoRelativePath : repoRelativePath[(idx + 1)..];
    }

    /// <summary>The immediate parent folder name plus the file name (e.g. "Hud/ActorHudCache.cs" for
    /// ".../src/FusionRpg.Injector/Hud/ActorHudCache.cs") — a `links` file's `Link` metadata groups it
    /// under one folder in the new project rather than flattening every linked file into the root.</summary>
    static string LastTwoSegments(string repoRelativePath)
    {
        var parts = repoRelativePath.Split('/');
        return parts.Length < 2 ? repoRelativePath : $"{parts[^2]}/{parts[^1]}";
    }

    static string BuildProjectCsproj(SplitManifest manifest, SplitProject project, string sharedName)
    {
        var sb = new StringBuilder();
        sb.Append("<Project Sdk=\"Microsoft.NET.Sdk\">\r\n");
        sb.Append($"  <Import Project=\"..\\{sharedName}\\CoreTests.Shared.props\" />\r\n");
        sb.Append("  <PropertyGroup>\r\n");
        // Every property the residual's own PropertyGroup sets directly (never moved to the shared
        // props -- A2 moves only package references and linked items, never property settings).
        // Missing TargetFramework here is exactly what NETSDK1013 caught the first time this ran for
        // real (map's own build+test gate, TVB5.4): an SDK-style project has no other source for it.
        sb.Append("    <TargetFramework>net8.0</TargetFramework>\r\n");
        sb.Append("    <ImplicitUsings>enable</ImplicitUsings>\r\n");
        sb.Append("    <Nullable>enable</Nullable>\r\n");
        sb.Append("    <IsPackable>false</IsPackable>\r\n");
        sb.Append("    <RootNamespace>FusionRpg.Core.Tests</RootNamespace>\r\n");
        sb.Append("    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>\r\n");
        sb.Append("  </PropertyGroup>\r\n");

        if (project.References.Count > 0 || project.Links.Count > 0 || project.Content.Count > 0)
        {
            sb.Append("  <ItemGroup>\r\n");
            foreach (var reference in project.References)
                sb.Append($"    <ProjectReference Include=\"..\\..\\{reference.Replace('/', '\\')}\" />\r\n");

            // Links name a REPO-RELATIVE source path anywhere in the tree (the three Injector files
            // under src/, DataTestStore.cs under a sibling test project) -- never assumed to live inside
            // the residual. Two levels up from tests/<Name>/ reaches the repo root; the Link metadata
            // keeps the file visually grouped under its immediate parent folder rather than dumping every
            // linked file flat into the project root.
            foreach (var link in project.Links)
            {
                var linkValue = LastTwoSegments(link).Replace('/', '\\');
                sb.Append($"    <Compile Include=\"..\\..\\{link.Replace('/', '\\')}\" Link=\"{linkValue}\" />\r\n");
            }

            // Content stays wherever it is on disk today -- a manifest content entry is the literal
            // csproj-relative Include text (project-relative for content that physically moved in via
            // `include`, like a candidate's own Goldens; `../`-prefixed for content shared from outside
            // the project, like gk-core/tests/fixtures/, which mirrors the residual's own convention exactly,
            // Link included so CopyToOutputDirectory does not try to create a literal ".." folder).
            foreach (var content in project.Content)
            {
                var include = content.Replace('/', '\\');
                var linkAttr = "";
                if (content.StartsWith("../", StringComparison.Ordinal) || content.StartsWith("..\\", StringComparison.Ordinal))
                {
                    var stripped = content.TrimStart('.', '/', '\\');
                    var linkPrefix = stripped.EndsWith("/**/*", StringComparison.Ordinal)
                        ? stripped[..^"/**/*".Length]
                        : stripped;
                    var linkBody = linkPrefix.Replace('/', '\\')
                        + (stripped.EndsWith("/**/*", StringComparison.Ordinal) ? "\\%(RecursiveDir)%(Filename)%(Extension)" : "");
                    linkAttr = $" Link=\"{linkBody}\"";
                }
                sb.Append($"    <None Include=\"{include}\"{linkAttr} CopyToOutputDirectory=\"PreserveNewest\" />\r\n");
            }

            sb.Append("  </ItemGroup>\r\n");
        }

        sb.Append("</Project>\r\n");
        return sb.ToString();
    }

    /// <summary>The shared props every Core test project imports: the package references the residual
    /// declares today, plus one linked `Compile` item per shared pattern. No `.csproj` of its own (A1) —
    /// each importing project compiles its own copy of the shared sources.</summary>
    static string BuildSharedProps(SplitManifest manifest, string residualCsprojText)
    {
        var sb = new StringBuilder();
        sb.Append("<Project>\r\n");
        // XML, not C# -- GeneratedHeader's `//` lines (and its "--", illegal inside an XML comment
        // body) are only valid in the C# attribute file. A bare `//` text node as a direct child of
        // <Project> is what MSB4067 caught here the first time this ran for real (a live NETSDK1013
        // fix immediately exposed this as the very next error).
        sb.Append("  <!-- Generated by `tools/FileMove split` from the manifest; never hand-edited.\r\n");
        sb.Append("       Regenerate by re-running the split tool; a hand edit is reverted by the next run. -->\r\n");
        sb.Append("  <ItemGroup>\r\n");

        foreach (Match m in PackageReferenceElement.Matches(residualCsprojText))
            sb.Append(Reindent(m.Value, "    ")).Append("\r\n");

        foreach (var pattern in manifest.Shared)
        {
            if (pattern.EndsWith("/**", StringComparison.Ordinal))
            {
                var prefix = pattern[..^"/**".Length].Replace('/', '\\');
                sb.Append($"    <Compile Include=\"$(MSBuildThisFileDirectory){prefix}\\**\\*.cs\" "
                    + $"Link=\"{prefix}\\%(RecursiveDir)%(Filename)%(Extension)\" />\r\n");
            }
            else
            {
                var file = pattern.Replace('/', '\\');
                sb.Append($"    <Compile Include=\"$(MSBuildThisFileDirectory){file}\" Link=\"{file}\" />\r\n");
            }
        }

        sb.Append("  </ItemGroup>\r\n");
        sb.Append("</Project>\r\n");
        return sb.ToString();
    }

    /// <summary>Imports the shared props once and drops what the props now provides: the residual's own
    /// `PackageReference`s (would otherwise duplicate the props' copies) and any explicit `Compile`/
    /// `None` item whose `Include` matches a `shared` pattern (files that just moved out from under it —
    /// the SDK's default globs need no edit for them, but an explicit item would dangle).</summary>
    static string EditResidualCsproj(string residualCsprojText, SplitManifest manifest, string sharedName)
    {
        var text = residualCsprojText;
        var importLine = $"  <Import Project=\"..\\{sharedName}\\CoreTests.Shared.props\" />";

        if (!text.Contains(importLine, StringComparison.Ordinal))
        {
            var open = ProjectOpenTag.Match(text);
            if (open.Success)
                text = text.Insert(open.Index + open.Length, Newline(text) + importLine);
        }

        text = PackageReferenceElement.Replace(text, "");

        text = ExplicitItemLine.Replace(text, m =>
        {
            var include = m.Groups["inc"].Value.Replace('\\', '/');
            return manifest.Shared.Any(p => SplitManifestValidator.MatchesPattern(include, p)) ? "" : m.Value;
        });

        return text;
    }

    /// <summary>The element's own text moved to a new indent: the first line's original leading
    /// whitespace is replaced, every continuation line keeps its relative indentation (so a paired
    /// element's `IncludeAssets`/`PrivateAssets` children stay indented under their parent).</summary>
    static string Reindent(string element, string indent)
    {
        var text = element.Trim('\r', '\n');
        var firstLineStart = text.Length - text.TrimStart(' ', '\t').Length;
        return indent + text[firstLineStart..];
    }

    /// <summary>The newline this text already uses. The split writes into files it did not create, and
    /// hard-coding `\r\n` put a CR at the end of an LF file's `<Project>` line — a mixed-ending file on
    /// disk (the committed blob normalises to LF either way via `.gitattributes`, so nothing catches
    /// it, but the working copy disagrees with itself).</summary>
    static string Newline(string text) =>
        text.Contains("\r\n", StringComparison.Ordinal) ? "\r\n" : "\n";

    static string BuildInternalsVisibleTo(SplitManifest manifest)
    {
        var names = manifest.Projects
            .Where(p => p.CoreInternals)
            .Select(p => p.Name)
            .OrderBy(n => n, StringComparer.Ordinal);

        var sb = new StringBuilder();
        sb.Append(GeneratedHeader);
        sb.Append("\r\n");
        sb.Append("using System.Runtime.CompilerServices;\r\n\r\n");
        foreach (var name in names)
            sb.Append($"[assembly: InternalsVisibleTo(\"{name}\")]\r\n");
        return sb.ToString();
    }

    /// <summary>Adds one `&lt;Project Path=.../&gt;` LINE before the `/tests/` folder's closing tag,
    /// indented one level deeper than that tag and using the file's own newline. Null when the slnx has
    /// no such folder to add it to — a real environment error, not a normal refusal shape, but surfaced
    /// through the same `Refusal` field so a caller sees one place for "why didn't this plan".</summary>
    static string? AddSlnxEntry(string slnxText, string projectName)
    {
        var entryPath = $"tests/{projectName}/{projectName}.csproj";
        if (slnxText.Contains(entryPath, StringComparison.Ordinal)) return slnxText;

        var folder = TestsFolder.Match(slnxText);
        if (!folder.Success) return null;

        const string closeTag = "</Folder>";
        var closeTagIndex = folder.Index + folder.Length - closeTag.Length;

        // The close tag's own line indent (whitespace only, or the preceding text is not a line of its
        // own and the entry gets no indent). The previous shape inserted `entry + "\r\n  "` AT the
        // close tag, which kept its existing indent in front — two levels too deep — and used CRLF in a
        // repo whose `.gitattributes` pins `eol=lf`.
        var lineStart = closeTagIndex;
        while (lineStart > 0 && slnxText[lineStart - 1] != '\n') lineStart--;
        var candidateIndent = slnxText[lineStart..closeTagIndex];
        var indent = candidateIndent.All(char.IsWhiteSpace) ? candidateIndent : "";

        var entry = $"{indent}  <Project Path=\"{entryPath}\" />";
        return slnxText[..lineStart] + entry + Newline(slnxText) + slnxText[lineStart..];
    }
}
